# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: BuildSignAndRelease

on:
  push:
    branches: [ "master" ]

jobs:
  BuildSignAndRelease:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set default Xamarin SDK versions
      run: |
        $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.12 --android=13.2
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: | 
          6.0.x
          7.0.x
          
    - name: Install dependencies
      run: nuget restore MWP.sln

    - name: Generate build number
      id: buildnumber
      uses: onyxmueller/build-tag-number@v1
      with:
        token: ${{secrets.github_token}}
        
    - name: Print new build number
      run: echo "Build number is $BUILD_NUMBER"
      
    - name: Update AndroidManifest.xml
      uses: damienaicheh/update-android-version-manifest-action@v1.0.0
      with:
        android-manifest-path: './Properties/AndroidManifest.xml'
        version-code: ${{ steps.buildnumber.outputs.build_number }}
        version-name: ${{ steps.buildnumber.outputs.build_number }}
        print-file: true
      
    - name: BuildAndSign
      uses: bradyjoslin/xamarinandroid-signedbuild-action@v1
      with:
          csproj_path: MWP.csproj
          signing_keystore: ${{ secrets.KEYSTORE }}
          keystore_password: ${{ secrets.KEYSTORE_PASS }}
          signing_key_alias: ${{ secrets.KEY_ALIAS }}
          signing_key_password: ${{ secrets.KEY_PASS }}

#https://github.com/marvinpinto/action-automatic-releases
    - name: Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "latest"
          title: "${{ steps.buildnumber.outputs.build_number }}"
          files: |
            LICENSE.txt
            bin/Release/**Signed.apk
