# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set default Xamarin SDK versions
      run: |
        $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.12 --android=13.2
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: | 
          6.0.x
          7.0.x
          
    - name: Install dependencies
      run: nuget restore Ass_Pain.sln

    - name: Build
      run: msbuild Ass_Pain.csproj /t:PackageForAndroid /p:Configuration=Debug
    - name: Sign
    - uses: bradyjoslin/xamarinandroid-signedbuild-action@v1
      with:
          csproj_path: Ass_Pain.csproj
          signing_keystore: ${{ secrets.KEYSTORE }}
          keystore_password: ${{ secrets.KEYSTORE_PASS }}
          signing_key_alias: ${{ secrets.KEY_ALIAS }}
          signing_key_password: ${{ secrets.KEY_PASS }}
    - uses: actions/upload-artifact@v3
      with:
          name: artifact
          path: bin/Release/**Signed.apk
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          files: |
            LICENSE.txt
            *Signed.apk
